CREATE TABLE USERS (
	ID		VARCHAR(10) PRIMARY KEY, 
	NAME 	VARCHAR(20) NOT NULL, 
	PASSWD	VARCHAR(20) NOT NULL
)


CREATE TABLE USERS (
	ID		VARCHAR(10) PRIMARY KEY, 
	LEVEL	TINYINT(3) NOT NULL, 
	NAME 	VARCHAR(20) NOT NULL, 
	PASSWD	VARCHAR(20) NOT NULL,
	EMAIL 	VARCHAR(100) NOT NULL, 
	LOGIN	INT(11) NOT NULL,
	RECOMMEND	INT(11) NOT NULL	
)